version: "3.8"
services:
  nodeserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: ./TusWebApplication
    ports:
      - "5120:5000"
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
